# Generated by Django 3.2.23 on 2023-11-17 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название древовидного меню')),
            ],
            options={
                'verbose_name': 'Название древовидного меню',
                'verbose_name_plural': 'Название древовидного меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название меню')),
                ('url', models.SlugField(max_length=200, unique=True, verbose_name='url-адрес')),
                ('main_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_menus', to='tree_menu.menu', verbose_name='Название древовидного меню')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree_menu.menuitem', verbose_name='Родительское меню')),
            ],
            options={
                'verbose_name': 'Древовидное меню',
                'verbose_name_plural': 'Древовидное меню',
            },
        ),
    ]
